### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by TCRLABS** [chetanraje/css-shadow-generator#2]
**Describe the bug**
The Result section of the website (`Text-Area`) is Editable...

**To Reproduce**
1. Go to '[...website.com](https://chetanraje.github.io/boxshadowgenerator/)'
2. Click on 'Result Space `Text-Area`'
3. Start Typing....
4. See error...

**Expected behavior**
To avoid copying the wrong style by means of miss-type or miss clicks on the text area (result) it has to be Read Only since there is input functionality in the result section.

**Screenshots**
![Box-Shadow-Generator (1)](https://user-images.githubusercontent.com/87260202/186166943-58a51c15-a69a-474f-81e6-ce7178c417cb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 11
 - Browser [e.g. chrome, safari] - Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - Vivo S1
 - OS: [e.g. iOS8.1] - Android 12
 - Browser [e.g. stock browser, safari] - Chrome

**Comment by chetanraje** [comment]
### Fixed
Thanks For Letting Us Know...
